import { invoke } from "@tauri-apps/api/core";
import "./styles.css";

type Side = "local" | "remote";
type FileKind = "folder" | "file";
type FileEntry = { name: string; path: string; kind: FileKind; size: number; modified: number; extension: string; permissions?: string };
type DirectoryListing = { path: string; entries: FileEntry[] };
type SearchResult = FileEntry & { side: Side; relative_path: string };
type Profile = { id: string; name: string; host: string; port: number; username: string; remotePath: string };

const fallbackLocal: FileEntry[] = [
  { name: "Desktop", path: "Desktop", kind: "folder", size: 0, modified: Date.now(), extension: "" },
  { name: "Documents", path: "Documents", kind: "folder", size: 0, modified: Date.now(), extension: "" },
  { name: "Downloads", path: "Downloads", kind: "folder", size: 0, modified: Date.now(), extension: "" },
  { name: "Projects", path: "Projects", kind: "folder", size: 0, modified: Date.now(), extension: "" },
  { name: "Read me.txt", path: "Read me.txt", kind: "file", size: 1840, modified: Date.now() - 86400000, extension: "txt" }
];
const fallbackRemote: FileEntry[] = [
  { name: "backups", path: "/home/user/backups", kind: "folder", size: 0, modified: Date.now() - 86400000 * 2, extension: "" },
  { name: "public_html", path: "/home/user/public_html", kind: "folder", size: 0, modified: Date.now() - 86400000 * 4, extension: "" },
  { name: "deploy.sh", path: "/home/user/deploy.sh", kind: "file", size: 4210, modified: Date.now() - 86400000 * 8, extension: "sh", permissions: "rwxr-xr-x" },
  { name: "site-config.json", path: "/home/user/site-config.json", kind: "file", size: 920, modified: Date.now() - 86400000 * 12, extension: "json" }
];

const state = {
  localPath: "", remotePath: "/home/user", localEntries: fallbackLocal, remoteEntries: fallbackRemote,
  profiles: loadProfiles(), activeProfile: null as Profile | null, searchOpen: false, searchQuery: "", searchScope: "everywhere", searchType: "all", searchDate: "any", searchContent: false,
  searchResults: [] as SearchResult[], queue: [] as { id: number; label: string; status: string; progress: number }[], notice: "Ready when you are.", dragging: null as { side: Side; entry: FileEntry } | null
};

function loadProfiles(): Profile[] { try { return JSON.parse(localStorage.getItem("harbor-profiles") ?? "[]") as Profile[]; } catch { return []; } }
function saveProfiles() { localStorage.setItem("harbor-profiles", JSON.stringify(state.profiles)); }
function esc(value: string) { return value.replace(/[&<>"']/g, (character) => ({ "&": "&amp;", "<": "&lt;", ">": "&gt;", '"': "&quot;", "'": "&#039;" })[character] ?? character); }
function formatSize(bytes: number) { if (!bytes) return "—"; if (bytes < 1024) return `${bytes} B`; if (bytes < 1024 * 1024) return `${(bytes / 1024).toFixed(1)} KB`; if (bytes < 1024 * 1024 * 1024) return `${(bytes / 1024 / 1024).toFixed(1)} MB`; return `${(bytes / 1024 / 1024 / 1024).toFixed(1)} GB`; }
function formatDate(timestamp: number) { return timestamp ? new Intl.DateTimeFormat(undefined, { month: "short", day: "numeric", year: "numeric" }).format(new Date(timestamp)) : "—"; }
function icon(entry: FileEntry) { return entry.kind === "folder" ? "▰" : entry.extension === "sh" ? "⌁" : "▫"; }

function render() {
  const app = document.querySelector<HTMLDivElement>("#app")!;
  app.innerHTML = `<main class="shell">
    <header class="topbar"><div class="brand"><span class="brand-mark">⌁</span><span>Harbor</span><small>FILE</small></div><div class="top-actions"><button class="quiet-button" id="search-toggle"><span class="shortcut">⌘ K</span> Find files</button><button class="quiet-button" id="new-profile">+ New connection</button><button class="avatar">${state.activeProfile?.username?.slice(0, 1).toUpperCase() ?? "D"}</button></div></header>
    <section class="workspace-head"><div><p class="eyebrow">WORKSPACE</p><h1>${state.activeProfile ? esc(state.activeProfile.name) : "Local files"}</h1><p class="subtle">${esc(state.notice)}</p></div><div class="connection-status ${state.activeProfile ? "is-connected" : ""}"><span class="status-dot"></span>${state.activeProfile ? `Connected to ${esc(state.activeProfile.host)}` : "No remote connection"}</div></section>
    <section class="toolbar"><button class="tool-button" id="up-local">↑ <span>Up</span></button><button class="tool-button" id="refresh">↻ <span>Refresh</span></button><span class="toolbar-divider"></span><button class="tool-button" id="queue-toggle">⇢ <span>Transfers</span><b>${state.queue.length || ""}</b></button><div class="profile-picker"><span>REMOTE</span><select id="profile-select"><option value="">Choose a saved server</option>${state.profiles.map((p) => `<option value="${esc(p.id)}" ${state.activeProfile?.id === p.id ? "selected" : ""}>${esc(p.name)} · ${esc(p.host)}</option>`).join("")}</select></div></section>
    ${state.searchOpen ? renderSearch() : ""}<section class="panes">${renderPane("local", "On this Mac", state.localPath || "Home")}<div class="transfer-rail"><div class="rail-line"></div><button id="upload-action" title="Upload selected file">→</button><button id="download-action" title="Download selected file">←</button><div class="rail-line"></div></div>${renderPane("remote", state.activeProfile ? state.remotePath : "Connect a server", state.activeProfile ? state.remotePath : "SFTP / SCP / FTP")}</section>
    ${state.queue.length ? renderQueue() : ""}<footer class="statusbar"><span><i class="status-dot"></i>${esc(state.notice)}</span><span>Drag files between panels to transfer</span></footer></main>`;
  bindEvents();
}

function renderPane(side: Side, title: string, path: string) {
  const entries = side === "local" ? state.localEntries : state.remoteEntries;
  return `<article class="pane ${side}-pane" data-side="${side}"><div class="pane-head"><div><span class="pane-icon">${side === "local" ? "⌂" : "◉"}</span><strong>${title}</strong></div><button class="pane-menu">•••</button></div><div class="pathbar"><button class="home-button">⌂</button><span>${esc(path)}</span><button class="path-add">+</button></div><div class="column-head"><span>Name</span><span>Size</span><span>Modified</span></div><div class="file-list" data-side="${side}">${entries.map((entry) => `<div class="file-row" draggable="true" data-path="${esc(entry.path)}"><span class="file-name"><i>${icon(entry)}</i>${esc(entry.name)}</span><span>${formatSize(entry.size)}</span><span>${formatDate(entry.modified)}</span></div>`).join("")}${!entries.length ? `<div class="empty-state">No files here yet.</div>` : ""}</div><div class="pane-footer"><span>${entries.length} items</span><button class="filter-button">Filter</button></div></article>`;
}

function renderSearch() {
  return `<section class="search-dock"><div class="search-title"><div><p class="eyebrow">FIND FILES</p><h2>Search your workspace</h2></div><button id="close-search" class="close-button">×</button></div><div class="search-controls"><label class="search-input"><span>⌕</span><input id="search-query" value="${esc(state.searchQuery)}" placeholder="Try “logs”, “.pdf”, or “invoice”" autofocus /></label><button class="primary-button" id="run-search">Search</button></div><div class="filter-row"><label>Look in <select id="search-scope"><option value="everywhere" ${state.searchScope === "everywhere" ? "selected" : ""}>Everywhere</option><option value="local" ${state.searchScope === "local" ? "selected" : ""}>This Mac</option><option value="remote" ${state.searchScope === "remote" ? "selected" : ""}>Remote server</option></select></label><label>Kind <select id="search-type"><option value="all" ${state.searchType === "all" ? "selected" : ""}>Everything</option><option value="file" ${state.searchType === "file" ? "selected" : ""}>Files only</option><option value="folder" ${state.searchType === "folder" ? "selected" : ""}>Folders only</option><option value="pdf" ${state.searchType === "pdf" ? "selected" : ""}>PDFs</option><option value="image" ${state.searchType === "image" ? "selected" : ""}>Images</option></select></label><label>Modified <select id="search-date"><option value="any" ${state.searchDate === "any" ? "selected" : ""}>Any time</option><option value="today" ${state.searchDate === "today" ? "selected" : ""}>Today</option><option value="week" ${state.searchDate === "week" ? "selected" : ""}>Past week</option><option value="month" ${state.searchDate === "month" ? "selected" : ""}>Past month</option></select></label><label class="check-label"><input type="checkbox" id="search-content" ${state.searchContent ? "checked" : ""}/> Search inside files</label></div>${state.searchResults.length ? `<div class="results-heading"><span>${state.searchResults.length} matches</span><span>Name · Location · Modified</span></div><div class="results-list">${state.searchResults.map((result) => `<div class="result-row"><span class="file-name"><i>${icon(result)}</i>${esc(result.name)}</span><span class="result-location">${result.side === "local" ? "On this Mac" : "Remote"} · ${esc(result.relative_path)}</span><span>${formatDate(result.modified)}</span><button data-reveal="${esc(result.path)}" data-side="${result.side}">Open</button></div>`).join("")}</div>` : `<div class="search-hint"><span class="hint-icon">⌕</span><p>Search across local and remote files with plain language.<br/><small>Results will show the exact location and let you jump straight there.</small></p></div>`}</section>`;
}

function renderQueue() { return `<section class="queue"><div><p class="eyebrow">TRANSFER QUEUE</p><h3>${state.queue.length} operation${state.queue.length === 1 ? "" : "s"}</h3></div><div class="queue-items">${state.queue.map((item) => `<div class="queue-item"><span class="queue-spinner">◌</span><span>${esc(item.label)}</span><span class="queue-progress"><i style="width:${item.progress}%"></i></span><small>${item.status}</small></div>`).join("")}</div></section>`; }
async function invokeSafe<T>(command: string, args: Record<string, unknown>, fallback: T): Promise<T> { try { return await invoke<T>(command, args); } catch { return fallback; } }

async function loadLocal(path = state.localPath) { const listing = await invokeSafe<DirectoryListing>("read_local_directory", { path }, { path, entries: fallbackLocal }); state.localPath = listing.path; state.localEntries = listing.entries; render(); }
async function loadRemote() { if (!state.activeProfile) return; const password = await invokeSafe<string>("get_credential", { profileId: state.activeProfile.id }, ""); if (!password) { state.notice = "Add the server password to connect."; render(); openProfileDialog(); return; } const listing = await invokeSafe<DirectoryListing>("list_remote_directory", { config: { ...state.activeProfile }, password, path: state.remotePath }, { path: state.remotePath, entries: fallbackRemote }); state.remotePath = listing.path; state.remoteEntries = listing.entries; state.notice = `Connected to ${state.activeProfile.host}`; render(); }

async function runSearch() {
  state.searchQuery = document.querySelector<HTMLInputElement>("#search-query")?.value ?? ""; state.searchScope = document.querySelector<HTMLSelectElement>("#search-scope")?.value ?? "everywhere"; state.searchType = document.querySelector<HTMLSelectElement>("#search-type")?.value ?? "all"; state.searchDate = document.querySelector<HTMLSelectElement>("#search-date")?.value ?? "any"; state.searchContent = document.querySelector<HTMLInputElement>("#search-content")?.checked ?? false;
  const criteria = { query: state.searchQuery, kind: state.searchType, date: state.searchDate, content: state.searchContent }; let results: SearchResult[] = [];
  if (state.searchScope !== "remote") results.push(...await invokeSafe<SearchResult[]>("search_local", { root: state.localPath, criteria }, localSearch(state.localEntries, "local", criteria)));
  if (state.searchScope !== "local" && state.activeProfile) { const password = await invokeSafe<string>("get_credential", { profileId: state.activeProfile.id }, ""); results.push(...await invokeSafe<SearchResult[]>("search_remote", { config: { ...state.activeProfile }, password, root: state.remotePath, criteria }, localSearch(state.remoteEntries, "remote", criteria))); }
  state.searchResults = results; render();
}

function localSearch(entries: FileEntry[], side: Side, criteria: { query: string; kind: string; date: string; content: boolean }): SearchResult[] { const age = criteria.date === "today" ? 1 : criteria.date === "week" ? 7 : criteria.date === "month" ? 30 : 0; const cutoff = age ? Date.now() - age * 86400000 : 0; return entries.filter((entry) => (!criteria.query || entry.name.toLowerCase().includes(criteria.query.toLowerCase())) && (criteria.kind === "all" || criteria.kind === entry.kind || (criteria.kind === "pdf" && entry.extension === "pdf") || (criteria.kind === "image" && ["png", "jpg", "jpeg", "gif", "webp"].includes(entry.extension))) && (!cutoff || entry.modified >= cutoff)).map((entry) => ({ ...entry, side, relative_path: entry.path })); }

function bindEvents() {
  document.querySelector("#search-toggle")?.addEventListener("click", () => { state.searchOpen = true; render(); }); document.querySelector("#close-search")?.addEventListener("click", () => { state.searchOpen = false; render(); }); document.querySelector("#run-search")?.addEventListener("click", runSearch); document.querySelector<HTMLInputElement>("#search-query")?.addEventListener("keydown", (event) => { if (event.key === "Enter") runSearch(); }); document.querySelector("#new-profile")?.addEventListener("click", openProfileDialog); document.querySelector("#refresh")?.addEventListener("click", () => { void loadLocal(); void loadRemote(); }); document.querySelector("#up-local")?.addEventListener("click", () => void loadLocal("..")); document.querySelector<HTMLSelectElement>("#profile-select")?.addEventListener("change", (event) => { const id = (event.target as HTMLSelectElement).value; state.activeProfile = state.profiles.find((profile) => profile.id === id) ?? null; if (state.activeProfile) void loadRemote(); else render(); });
  document.querySelectorAll<HTMLDivElement>(".file-row").forEach((row) => { row.addEventListener("dragstart", () => { const side = row.closest<HTMLElement>(".pane")?.dataset.side as Side; const entries = side === "local" ? state.localEntries : state.remoteEntries; state.dragging = { side, entry: entries.find((entry) => entry.path === row.dataset.path) ?? entries[0] }; }); row.addEventListener("dblclick", () => { const side = row.closest<HTMLElement>(".pane")?.dataset.side as Side; const entry = (side === "local" ? state.localEntries : state.remoteEntries).find((item) => item.path === row.dataset.path); if (entry?.kind === "folder") { if (side === "local") void loadLocal(entry.path); else { state.remotePath = entry.path; void loadRemote(); } } }); });
  document.querySelectorAll<HTMLElement>(".file-list").forEach((list) => { list.addEventListener("dragover", (event) => event.preventDefault()); list.addEventListener("drop", () => { const target = list.dataset.side as Side; if (state.dragging && target !== state.dragging.side) void transfer(state.dragging.side, state.dragging.entry); }); }); document.querySelector("#upload-action")?.addEventListener("click", () => { const entry = state.localEntries.find((item) => item.kind === "file"); if (entry) void transfer("local", entry); }); document.querySelector("#download-action")?.addEventListener("click", () => { const entry = state.remoteEntries.find((item) => item.kind === "file"); if (entry) void transfer("remote", entry); }); document.querySelectorAll<HTMLButtonElement>("[data-reveal]").forEach((button) => button.addEventListener("click", async () => { const path = button.dataset.reveal ?? ""; if (button.dataset.side === "local") await invokeSafe("reveal_local_path", { path }, null); state.notice = `Opening ${path}`; render(); }));
}

async function transfer(from: Side, entry: FileEntry) { if (!state.activeProfile) { state.notice = "Choose a server before transferring files."; render(); return; } const password = await invokeSafe<string>("get_credential", { profileId: state.activeProfile.id }, ""); const id = Date.now(); state.queue.push({ id, label: `${from === "local" ? "Uploading" : "Downloading"} ${entry.name}`, status: "Starting", progress: 12 }); render(); const result = await invokeSafe<string>("transfer_file", { config: { ...state.activeProfile }, password, direction: from === "local" ? "upload" : "download", localPath: from === "local" ? entry.path : "", remotePath: from === "local" ? `${state.remotePath}/${entry.name}` : entry.path }, "Preview mode: build the Mac app to transfer files."); const item = state.queue.find((queueItem) => queueItem.id === id); if (item) { item.progress = 100; item.status = "Complete"; } state.notice = result; render(); }

function openProfileDialog() { const existing = document.querySelector(".dialog-backdrop"); if (existing) existing.remove(); document.body.insertAdjacentHTML("beforeend", `<div class="dialog-backdrop"><form class="dialog" id="profile-form"><button type="button" class="close-button" id="close-dialog">×</button><p class="eyebrow">NEW CONNECTION</p><h2>Connect to a server</h2><p class="subtle">Passwords are kept in the macOS Keychain, never in the app profile.</p><label>Profile name<input name="name" placeholder="Production server" required /></label><div class="two-fields"><label>Host<input name="host" placeholder="sftp.example.com" required /></label><label>Port<input name="port" type="number" value="22" required /></label></div><label>Username<input name="username" placeholder="your username" required /></label><label>Password<input name="password" type="password" placeholder="••••••••" required /></label><label>Remote folder<input name="remotePath" value="/home/" /></label><button class="primary-button" type="submit">Save and connect</button></form></div>`); document.querySelector("#close-dialog")?.addEventListener("click", () => document.querySelector(".dialog-backdrop")?.remove()); document.querySelector<HTMLFormElement>("#profile-form")?.addEventListener("submit", async (event) => { event.preventDefault(); const data = new FormData(event.currentTarget as HTMLFormElement); const profile: Profile = { id: crypto.randomUUID(), name: String(data.get("name")), host: String(data.get("host")), port: Number(data.get("port")), username: String(data.get("username")), remotePath: String(data.get("remotePath")) }; state.profiles.push(profile); saveProfiles(); await invokeSafe("save_credential", { profileId: profile.id, password: String(data.get("password")) }, null); state.activeProfile = profile; state.remotePath = profile.remotePath; document.querySelector(".dialog-backdrop")?.remove(); await loadRemote(); }); }

render(); void loadLocal();
